version: '3'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: antragsgruen
    ports: 
      - "3306:3306"  
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    image: eu.gcr.io/wir2020-test/antragsgruen:4.6.3.1
    build: app
    environment:
      ANTRAGSGRUEN_MYSQL_HOST: db
      ANTRAGSGRUEN_MYSQL_DB: antragsgruen
      ANTRAGSGRUEN_MYSQL_USER: root
      ANTRAGSGRUEN_MYSQL_PASSWORD: my-secret-pw
      ANTRAGSGRUEN_DOMAIN: "http://wir2020.local/"
      ANTRAGSGRUEN_SMTP_HOST: smtp.gmx.net
      ANTRAGSGRUEN_SMTP_PORT: 587
      ANTRAGSGRUEN_SMTP_AUTH_TYPE: plain_tls
      ANTRAGSGRUEN_SMTP_ENCRYPTION: tls
      ANTRAGSGRUEN_SMTP_USER: harald.wellmann@gmx.de
      ANTRAGSGRUEN_SMTP_PASSWORD: "******"
      ANTRAGSGRUEN_MAIL_FROM_NAME: "Antragsgrün Admininstrator"
      ANTRAGSGRUEN_MAIL_FROM_EMAIL: "******@gmx.de"
      
    ports:
    - "80:80"

